services:
  # Backend API Service (DuckDB)
  - type: web
    name: hesocial-api
    runtime: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_TYPE
        value: duckdb
      - key: CORS_ORIGINS
        value: https://hesocial-frontend.onrender.com,http://localhost:3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: static
    name: hesocial-frontend
    buildCommand: npm run build:frontend
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://hesocial-api.onrender.com
      - key: VITE_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html