[workspace]
members = ["crates/core", "crates/worker"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "UNLICENSED"
rust-version = "1.85"

[workspace.dependencies]
axum = { version = "0.8.3", default-features = false, features = ["json", "query"] }
base64 = "0.22.1"
bcrypt = "0.15.1"
getrandom = { version = "0.2.16", features = ["js"] }
hmac = "0.12.1"
pbkdf2 = "0.12.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
sha2 = "0.10.8"
tower-service = "0.3.3"
worker = { version = "0.8.5", default-features = false, features = ["http"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
